[package]
name = "docq-synth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
docq-core = { workspace = true }
docq-model = { workspace = true, features = ["llm"] }
docq-retrieve = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
regex = "1"

[dev-dependencies]
docq-indexer = { workspace = true }
docq-storage = { workspace = true }
tempfile = "3"
